services:

  haproxy-mailcow:
    build:
      context: .
      dockerfile: ../../front/haproxy.dockerfile
    #image: haproxy:latest
    container_name: haproxy-mailcow
    restart: always
    depends_on:
      - nginx-mailcow
    ports:
      # Services mail
      - "${SMTP_PORT:-25}:25"     # SMTP
      - "${SUBMISSION_PORT:-587}:587"   # SMTP Submission
      - "${SMTPS_PORT:-465}:465"   # SMTPS
      - "${IMAP_PORT:-143}:143"   # IMAP
      - "${IMAPS_PORT:-993}:993"   # IMAPS
      - "${POP_PORT:-110}:110"   # POP3
      - "${POPS_PORT:-995}:995"   # POP3S
      - "${SIEVE_PORT:-4190}:4190"   # SIEVE
    volumes:
      # Configuration HAProxy spécifique pour mailcow (avec IPv6)
      - ./data/conf/haproxy:/usr/local/etc/haproxy:ro
      # Certificats SSL générés par ACME
      - ./data/assets/ssl/:/etc/ssl/certs/haproxy:ro
    networks:
      # Connexion au réseau mailcow pour accéder aux services
      mailcow-network:
        ipv4_address: 172.22.1.200
        ipv6_address: fd4d:6169:6c63:6f77::0200
    environment:
      - TZ=${TZ:-Europe/Paris}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Suppression de tous les ports exposés (gérés par HAProxy)
  # Utilisation de !reset pour vider complètement la liste des ports
  mysql-mailcow:
    ports: !reset []
  
  redis-mailcow:
    ports: !reset []
  
  dovecot-mailcow:
    ports: !reset []
    volumes:
      - ../../front/data/certs/example.net/:/etc/ssl/mail/:ro
  postfix-mailcow:
    ports: !reset []
    volumes:
      - ../../front/data/certs/example.net/:/etc/ssl/mail/:ro
  
  nginx-mailcow:
    ports: !reset []

  acme-mailcow:
      entrypoint:
        - /bin/sh
        - -c
        - |
          if [ /var/lib/acme/cert.pem -nt /var/lib/acme/mailcow.pem ] 2>/dev/null || [ ! -f /var/lib/acme/mailcow.pem ]; then
            cat /var/lib/acme/cert.pem /var/lib/acme/key.pem > /var/lib/acme/mailcow.pem
            echo "$$(date): Certificat Mailcow initialisé au démarrage"
            docker kill -s USR2 haproxy-mailcow 2>/dev/null || true
          fi
          exec /sbin/tini -g -- /srv/acme.sh
      labels:
        # Hook HAProxy via Ofelia - Vérifie les certificats toutes les 2 minutes et reload HAProxy si un certificat a changé
        ofelia.enabled: "true"
        ofelia.job-exec.acme_haproxy_hook.schedule: "@daily"
        ofelia.job-exec.acme_haproxy_hook.no-overlap: "true"
        ofelia.job-exec.acme_haproxy_hook.command: "/bin/sh -c 'if [ /var/lib/acme/cert.pem -nt /var/lib/acme/mailcow.pem ] 2>/dev/null || [ ! -f /var/lib/acme/mailcow.pem ]; then cat /var/lib/acme/cert.pem /var/lib/acme/key.pem > /var/lib/acme/mailcow.pem && echo \"$$(date): Certificat Mailcow mis à jour via ACME\" && docker kill -s USR2 haproxy-mailcow 2>/dev/null || true; fi'"
      

  ofelia-mailcow:
      depends_on:
        - sogo-mailcow
        - dovecot-mailcow
        - acme-mailcow

# Redéfinition des volumes avec un chemin personnalisé
# Modifiez MAILCOW_DATA_PATH dans mailcow.conf pour changer le chemin de base
volumes:
  vmail-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/vmail
  vmail-index-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/vmail-index
  mysql-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/mysql
  mysql-socket-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/mysql-socket
  redis-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/redis
  rspamd-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/rspamd
  postfix-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/postfix
  postfix-tlspol-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/postfix-tlspol
  crypt-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/crypt
  sogo-web-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/sogo-web
  sogo-userdata-backup-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/sogo-userdata-backup
  clamd-db-vol-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MAILCOW_DATA_PATH:-/mnt/mailcow-data}/clamd-db
